variable "lambda_arn" {
  type        = string
  description = "ARN of the lambda function"
}

variable "http_method" {
  type        = string
  description = "HTTP method to use for the API Gateway"
  default     = "POST"
}

variable "api_gateway_id" {
  type        = string
  description = "ID of the API Gateway"
}

variable "api_gateway_name" {
  type        = string
  description = "Name of the API Gateway"
}

variable "path_resource_id" {
  type        = string
  description = "ID of the API Gateway path or root resource"
}

variable "api_gateway_iam_role_name" {
  type        = string
  description = "Name of the IAM role for the API Gateway"
}

variable "listen_path" {
  type        = string
  description = "Path to listen on for the API Gateway, single level only"
}

variable "tags" {
  type        = map(string)
  description = "Tags to apply to the resources generated by this module"
}

locals {
  tags = merge(var.tags, {
    "Source" = "Terraform"
    "Module" = "rest-api-gateway-lambda-endpoint"
  })
  lambda_name             = split(":", var.lambda_arn)[6]
  lambda_region           = split(":", var.lambda_arn)[3]
  normalised_gateway_name = replace(var.api_gateway_name, ".", "_")
}
